//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod crontab;
pub mod crontab_result;
pub mod db_registry;
pub mod dynamic_monitoring;
pub mod dynamic_monitoring_summary;
pub mod js_result;
pub mod js_worker;
pub mod kv;
pub mod monitoring_uuid;
pub mod static_file;
pub mod static_monitoring;
pub mod task;
pub mod token;
pub mod traffic_current_total;
pub mod traffic_possible_data_loss;
pub mod traffic_snapshot;
