//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "traffic_current_total")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub uuid_id: i16,
    pub interface_name: String,
    pub boot_id: Option<String>,
    pub ifindex: Option<i32>,
    pub counter_received: i64,
    pub counter_transmitted: i64,
    pub report_time: i64,
    pub total_received: i64,
    pub total_transmitted: i64,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
